[package]
name = "linkheader"
version = "0.1.0"
authors = ["Arnau Siches <asiches@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
failure = "0.1"
percent-encoding = "1.0"
